
sudo: false
language: node_js

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_install:
  - npm install -g grunt-cli
  - true && `base64 --decode <<< ZXhwb3J0IEJST1dTRVJTVEFDS19VU0VSTkFNRT1icm93c2Vyc3RhY2tydW5uMQo=`
  - true && `base64 --decode <<< ZXhwb3J0IEJST1dTRVJTVEFDS19LRVk9NW5qc0d5emdqNkpWMmh3eUh1dHEK`

script:
  - cd runner/qunit
  - npm install
  - ./node_modules/.bin/browserstack-runner --verbose
  - cd karma/karma-browserstack-example && npm install && npm test
